    - name: Install docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true

    - name: add Dockers GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add Dockers repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        update_cache: true

    - name: install required library for docker.container
      apt:
        name:
          - python3-pip
          - python3-requests
        state: present
        update_cache: yes


    - name: Install XFCE4 desktop environment
      apt:
        name:
          - xfce4
          - xfce4-goodies
        state: present
        update_cache: yes

    - name: Install LightDM
      apt:
        name: lightdm
        state: present
        update_cache: yes

    - name: Install Firefox
      apt:
        name: firefox-esr
        state: present



    - name: create linux user
      user:
        name: linuxuser
        password: "{{ 'bebras' | password_hash('sha512') }}"
        state: present
