    - name: Install docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true

    - name: add Dockers GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add Dockers repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        update_cache: true

    - name: install required library for docker.container
      apt:
        name:
          - python3-pip
          - python3-requests
        state: present
        update_cache: yes


    - name: Run lync text-browser container
      community.docker.docker_container:
        name: lynx-browser
        image: jess/lynx
        state: started



    - name: create linux user
      user:
        name: linuxuser
        password: "{{ 'bebras' | password_hash('sha512') }}"
        state: present
